# Site settings
title: Beats, Rye &amp; Types
subtitle: Beats, Rye &amp; Types with AQ and MRB. Music, Food, Programming.
description: > # this means to ignore newlines until "baseurl:"
  Your favorite podcast about Music, Food, and Programming
baseurl: "" # the subpath of your site, e.g. /blog/
copyright: "&#xA9; 2015 BEATS RYE TYPES, LLC"
author: Aaron Quint &amp; Michael Bernstein
keywords: music,food,programming,computers,aq,mrb,brooklyn
url: "http://beatsryetypes.com" # the base hostname & protocol for your site
twitter_username: beatsryetypes
github_username:  beatsryetypes
paginate: 5

# Build settings
markdown: kramdown
